version: "3.9"
services:
  rails:
    build: .
    command: ["bin/rails", "s", "-b", "0.0.0.0"]
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - bundle:/app/vendor/bundle
    depends_on:
      - mysql
    ports:
      - "49152:3000"
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
  bundle:
